services:
  users:
    build:
      context: ../
      dockerfile: dockerfiles/service.dockerfile
      args:
        - domain=users
    environment:
      - GRPC_URL=users:8081
      - HTTP_PORT=8082
      - MONGO_URI=mongodb://db/users
    depends_on:
      - db
    command: 'node /app/main.js'

  gateway:
    build:
      context: ../
      dockerfile: dockerfiles/service.dockerfile
      args:
        - domain=gateway
    environment:
      - USERS_SERVICE_GRPC_URL=users:8081
      - HTTP_PORT=8080
      - JWT_SECRET=123456789abcd
      - JWT_EXPIRES_IN=1d
      - TOKEN_COOKIE_NAME=authtoken
    depends_on:
      - users
    command: 'node /app/main.js'
    ports:
      - '8080:8080'

  db:
    image: bitnami/mongodb:4.4.14
    environment:
      - MONGODB_DISABLE_SYSTEM_LOG=true
      - MONGODB_ENABLE_JOURNAL=false
    logging:
      driver: none
